export const politicalGroups = [
	{
		acronym: "MDB",
		name: "Movimento Democrático Brasileiro",
		president: "Luiz Felipe Baleia Tenuto",
		number: 15,
	},
	{
		acronym: "PTB",
		name: "Partido Trabalhista Brasileiro",
		president: "Marcus Vinícius de Vasconcelos Ferreira",
		number: 14,
	},
	{
		acronym: "PDT",
		name: "Partido Democrático Trabalhista",
		president: "André Peixoto F. Lima",
		number: 12,
	},
	{
		acronym: "PT",
		name: "Partido dos Trabalhadores",
		president: "Gleisi Helena Hoffmann",
		number: 13,
	},
	{
		acronym: "PCdoB",
		name: "Partido Comunista do Brasil",
		president: "Luciana Barbosa de Oliveira Santos",
		number: 65,
	},
	{
		acronym: "AGIR",
		name: "AGIR",
		president: "Daniel S. Tourinho",
		number: 36,
	},
	{
		acronym: "PMN",
		name: "Partido da Mobilização Nacional",
		president: "Antonio Carlos Bosco Massarollo",
		number: 33,
	},
	{
		acronym: "CIDADANIA",
		name: "Cidadania",
		president: "Plínio Comte Leite Bittencourt",
		number: 23,
	},
	{
		acronym: "PV",
		name: "Partido Verde",
		president: "José Luiz de França Penna",
		number: 43,
	},
	{
		acronym: "Avante",
		name: "Avante",
		president: "Luis Henrique de Oliveira Resende",
		number: 70,
	},
	{
		acronym: "PP",
		name: "Progressistas",
		president: "Ciro Nogueira Lima Filho",
		number: 11,
	},
	{
		acronym: "PSTU",
		name: "Partido Socialista dos Trabalhadores Unificado",
		president: "José Maria de Almeida",
		number: 16,
	},
	{
		acronym: "PCB",
		name: "Partido Comunista Brasileiro",
		president: "Edmilson Silva Costa",
		number: 21,
	},
	{
		acronym: "PRTB",
		name: "Partido Renovador Trabalhista Brasileiro",
		president: "John Herberthe Calumbia Pinto Dos Santos",
		number: 28,
	},
	{
		acronym: "DC",
		name: "Democracia Cristã",
		president: "José Maria Eymaiel",
		number: 27,
	},
	{
		acronym: "PCO",
		name: "Partido da Causa Operária",
		president: "Rui Costa Pimenta",
		number: 29,
	},
	{
		acronym: "PODE",
		name: "Podemos",
		president: "Renata Hellmeister de Abreu",
		number: 19,
	},
	{
		acronym: "Republicanos",
		name: "Republicanos",
		president: "Marcos Antonio Pereira",
		number: 10,
	},
	{
		acronym: "PSOL",
		name: "Partido Socialismo e Liberdade",
		president: "Juliano Medeiros",
		number: 50,
	},
	{
		acronym: "PL",
		name: "Partido Liberal",
		president: "Valdemar Costa Neto",
		number: 22,
	},
	{
		acronym: "PSD",
		name: "Partido Social Democrático",
		president: "Gilberto Kassab",
		number: 55,
	},
	{
		acronym: "PATRIOTA",
		name: "Patriota",
		president: "Osvaldo Roma Altimari Resende",
		number: 51,
	},
	{
		acronym: "SOLIDARIEDADE",
		name: "Solidariedade",
		president: "Euripedes Gomes Macedo júnior",
		number: 77,
	},
	{
		acronym: "NOVO",
		name: "Partido Novo",
		president: "Eduardo Rodrigo Fernandes Ribeiro",
		number: 30,
	},
	{
		acronym: "REDE",
		name: "Rede Sustentabilidade",
		president: "Heloísa Helena Lima de Moraes",
		number: 18,
	},
	{
		acronym: "PMB",
		name: "Partido da Mulher Brasileira",
		president: "Suêd Haidar Nogueira",
		number: 35,
	},
	{
		acronym: "UP",
		name: "Unidade Popular",
		president: "Leonardo Pericles Vieira Roque",
		number: 80,
	},
	{
		acronym: "UNIÃO",
		name: "União Brasil",
		president: "Luciano Caldas Bivar",
		number: 44,
	},
];
