# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: rm -rf node_modules
      - run: yarn
      - run: yarn prisma migrate deploy
      - run: yarn build
      - run: |
          touch .env
          echo "${{secrets.PROD_ENV_FILE}}" > .env
      - run: pm2 stop server
      - run: pm2 delete server
      - run: pm2 start /build/server.js --name server
      - run: pm2 save
